image: archlinux
packages:
  - jdk11-openjdk
  - maven
sources:
  - https://git.sr.ht/~taum/sanshainMaven
tasks:
  - build: |
      cd sanshainMaven
      mvn compile -B
  - test: |
      cd sanshainMaven
      mvn test -B
