image: archlinux
packages:
  - openjdk17-src
  - maven
sources:
  - https://git.sr.ht/~taum/sanshainMaven
tasks:
  - build: |
      cd sanshainMaven
      mvn compile
  - test: |
      cd sanshainMaven
      mvn test
